name: student_gator_task
description: "Student Gator Task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  # State management
  flutter_bloc: ^8.1.5
  # An SVG rendering
  flutter_svg: ^2.0.10+1
  # For adapting screens and font size
  flutter_screenutil: ^5.9.1
  # Code generator
  freezed: ^2.5.3
  freezed_annotation: ^2.4.1
  # Flutter plugin for reading and writing simple key-value pairs locally.
  shared_preferences: ^2.2.3
  # Dependency injection
  get_it: ^7.7.0
  # Create dashed lines & create a dashed border
  fdottedline_nullsafety: ^2.0.1

dependency_overrides:
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.10
  analyzer: ^6.5.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/anim/
    - assets/icon/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

flutter_intl:
  enabled: true